### ISSUE TITLE
bugfix: as a middleware user - custom errorMessage shouldn't be required

### ISSUE THREAD

**Issue by davidmeirlevy** [prici-io/prici#31]
right now, errorMessage is a require field in both express middleware and nest guard.
it should be optional, and if not exists - a default error message will appear.

**Comment by madina0801** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by davidmeirlevy** [comment]
Assigned you ✌️

I believe the default message should be "payment required".
