### ISSUE TITLE
enhancement: improve NestJs support 

### ISSUE THREAD

**Issue by eladabramovich** [prici-io/prici#33]
Currently, when creating a new Prici SDK instance in a NestJs app the app does not know about
the SDK instance in any way. This means that the SDK does not work in tandem with the Nest runtime.
By abstracting the SDK instance in a custom module, the following could be achieved:

- A simpler interface to work with.
- Less setup work.
- Less boilerplate code.
- Adding support for projects that use `@nestjs/config`
and possibly other Nest related packages in the future.
- Passing default config options when instantiating
the SDK in a central place and then using them all over the app.

**Comment by davidmeirlevy** [comment]
Basically you want the SDK to be an injectable? and to have the guard as "given"?

sounds great. go for it !  🚀

**Comment by eladabramovich** [comment]
You are correct about the SDK being injectable. Not sure about what you meant by "given"
but basically, the SDK will be instantiated in a service that the new module will export
and I will add an optional  `defaultErrorMessage` property to `PriciSDKOptions` (for cases
where the user wants one default message for all routes that is not "payment required").

With these 2 changes, the guard doesn't have any required options anymore and can be
reduced to:
```typescript
@UseGuards(IsAllowedGuard())
```
P.S I was able to implement the guard in a slightly different way that doesn't require
invoking it with the `new` keyword
